apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: indichess
  labels:
    app: eureka-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      serviceAccountName: indichess-service-account
      containers:
      - name: eureka-server
        image: indichess/eureka-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
          name: http
        env:
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m"
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: indichess
  labels:
    app: eureka-server
spec:
  type: ClusterIP
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
    name: http
  selector:
    app: eureka-server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: eureka-server-pdb
  namespace: indichess
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: eureka-server
